/* eslint-disable */
/* Generated by react-to-web-component-compiler compile. No React runtime is included. */
const Fragment = Symbol.for("rwcb.fragment");
const ContextProvider = Symbol.for("rwcb.context-provider");
const Portal = Symbol.for("rwcb.portal");
const SuspenseBoundary = Symbol.for("rwcb.suspense");
let __rwcbCurrentInstance = null;
let __rwcbCurrentSuspenseFallback = null;

function h(type, props, ...children) {
  return { type, props: props || {}, children: children.flat(Infinity) };
}

const createElement = h;
const StrictMode = Fragment;

function useState(initialValue) {
  if (!__rwcbCurrentInstance) throw new Error("useState can only run during render.");
  return __rwcbCurrentInstance.useState(initialValue);
}

function useReducer(reducer, initialArg, init) {
  const [state, setState] = useState(() => init ? init(initialArg) : initialArg);
  const dispatch = (action) => setState((current) => reducer(current, action));
  return [state, dispatch];
}

function useMemo(factory, deps) {
  if (!__rwcbCurrentInstance) throw new Error("useMemo can only run during render.");
  return __rwcbCurrentInstance.useMemo(factory, deps);
}

function useCallback(callback, deps) {
  return useMemo(() => callback, deps);
}

function useRef(initialValue) {
  if (!__rwcbCurrentInstance) throw new Error("useRef can only run during render.");
  return __rwcbCurrentInstance.useRef(initialValue);
}

function useEffect(effect, deps) {
  if (!__rwcbCurrentInstance) throw new Error("useEffect can only run during render.");
  return __rwcbCurrentInstance.useEffect(effect, deps, false);
}

function useLayoutEffect(effect, deps) {
  if (!__rwcbCurrentInstance) throw new Error("useLayoutEffect can only run during render.");
  return __rwcbCurrentInstance.useEffect(effect, deps, true);
}

function useImperativeHandle(ref, create, deps) {
  const value = useMemo(create, deps);
  if (ref) ref.current = value;
  if (__rwcbCurrentInstance) __rwcbCurrentInstance.__rwcbPublicHandle = value;
}

function useContext(context) {
  if (!__rwcbCurrentInstance) throw new Error("useContext can only run during render.");
  return __rwcbCurrentInstance.__rwcbReadContext(context);
}

function useId() {
  if (!__rwcbCurrentInstance) throw new Error("useId can only run during render.");
  return __rwcbCurrentInstance.useId();
}

function useDeferredValue(value) { return value; }
function startTransition(callback) { return callback(); }
function useTransition() { return [false, startTransition]; }
function useInsertionEffect(effect, deps) { return useLayoutEffect(effect, deps); }
function useSyncExternalStore(subscribe, getSnapshot) {
  const [snapshot, setSnapshot] = useState(() => getSnapshot());
  useEffect(() => subscribe(() => setSnapshot(getSnapshot())), [subscribe, getSnapshot]);
  return snapshot;
}
function useDebugValue() {}

function createContext(defaultValue) {
  const context = { defaultValue, Provider: null };
  context.Provider = function Provider(props) {
    return { type: ContextProvider, props: { context, value: props.value }, children: props.children || [] };
  };
  context.Provider.__rwcbContextProvider = true;
  return context;
}

function createRef() { return { current: null }; }

const Children = {
  toArray(children) { return normalizeChildren(children); },
  count(children) { return normalizeChildren(children).length; },
  map(children, mapper) { return normalizeChildren(children).map(mapper); },
  forEach(children, mapper) { normalizeChildren(children).forEach(mapper); },
  only(children) {
    const items = normalizeChildren(children);
    if (items.length !== 1) throw new Error("Children.only expected one child.");
    return items[0];
  }
};

function cloneElement(element, props, ...children) {
  return { ...element, props: { ...(element?.props || {}), ...(props || {}) }, children: children.length ? children : element.children };
}

function isValidElement(value) {
  return Boolean(value && typeof value === "object" && "type" in value && "props" in value);
}

function forwardRef(render) {
  return { __rwcbForwardRef: true, render };
}

function memo(component) { return component; }
function createPortal(children, target) { return { type: Portal, props: { target }, children: [children] }; }

function Suspense(props) {
  return { type: SuspenseBoundary, props: { fallback: props.fallback }, children: props.children || [] };
}

function lazy(loader) {
  return function LazyComponent(props) {
    const [record, setRecord] = useState(() => ({ status: "pending", component: null, promise: null }));
    if (record.status === "resolved" && record.component) return h(record.component, props);
    if (!record.promise) {
      const promise = loader().then((module) => {
        setRecord({ status: "resolved", component: module.default || module, promise });
      });
      record.promise = promise;
    }
    return __rwcbCurrentSuspenseFallback;
  };
}

const React = {
  Children,
  Fragment,
  StrictMode,
  Suspense,
  cloneElement,
  createContext,
  createElement,
  createRef,
  forwardRef,
  isValidElement,
  lazy,
  memo,
  startTransition,
  useCallback,
  useContext,
  useDebugValue,
  useDeferredValue,
  useEffect,
  useId,
  useImperativeHandle,
  useInsertionEffect,
  useLayoutEffect,
  useMemo,
  useReducer,
  useRef,
  useState,
  useSyncExternalStore,
  useTransition
};

function defineComponentTag(tagName, Component, options = {}) {
  const propOptions = options.props || {};
  const eventOptions = options.events || {};
  const slotOptions = options.slots || {};
  const observed = Object.entries(propOptions)
    .filter(([, definition]) => definition?.attribute !== false)
    .map(([name, definition]) => definition?.attribute || toKebab(name));

  class CompiledReactElement extends HTMLElement {
    static observedAttributes = observed;

    constructor() {
      super();
      this.__rwcbProps = {};
      this.__rwcbHooks = [];
      this.__rwcbHookIndex = 0;
      this.__rwcbRenderQueued = false;
      this.__rwcbLayoutEffects = [];
      this.__rwcbEffects = [];
      this.__rwcbContextValues = new Map();
      this.__rwcbPortalContainers = [];
      this.__rwcbIdPrefix = tagName + "-" + Math.random().toString(36).slice(2);
      this.__rwcbPublicRef = { current: null };
      this.__rwcbPublicHandle = null;
      this.__rwcbRoot = options.shadow === false ? this : this.attachShadow({ mode: options.shadow?.mode || "open", delegatesFocus: Boolean(options.shadow?.delegatesFocus) });
      this.__rwcbMount = document.createElement("span");
      this.__rwcbMount.setAttribute("part", "compiled-mount");
      this.__rwcbRoot.append(this.__rwcbMount);
      applyStyles(this.__rwcbRoot, options.styles);
      for (const [name, definition] of Object.entries(propOptions)) {
        if (definition && "default" in definition) this.__rwcbProps[name] = definition.default;
      }
    }

    connectedCallback() {
      this.__rwcbRender();
    }

    disconnectedCallback() {
      for (const hook of this.__rwcbHooks) {
        if (hook && typeof hook.cleanup === "function") hook.cleanup();
      }
      this.__rwcbCleanupPortals();
    }

    attributeChangedCallback(attributeName, _oldValue, nextValue) {
      const entry = Object.entries(propOptions).find(([name, definition]) => (definition?.attribute || toKebab(name)) === attributeName);
      if (!entry) return;
      const [name, definition] = entry;
      this.__rwcbProps[name] = parseAttribute(nextValue, definition);
      this.__rwcbScheduleRender();
    }

    __rwcbScheduleRender() {
      if (this.__rwcbRenderQueued || !this.isConnected) return;
      this.__rwcbRenderQueued = true;
      queueMicrotask(() => {
        this.__rwcbRenderQueued = false;
        if (this.isConnected) this.__rwcbRender();
      });
    }

    __rwcbRender() {
      this.__rwcbHookIndex = 0;
      this.__rwcbLayoutEffects = [];
      this.__rwcbEffects = [];
      this.__rwcbCleanupPortals();
      const previous = __rwcbCurrentInstance;
      __rwcbCurrentInstance = this;
      try {
        const componentProps = {
          ...this.__rwcbProps,
          ...this.__rwcbCreateEventProps(),
          ...this.__rwcbCreateSlotProps()
        };
        const vnode = Component?.__rwcbForwardRef ? Component.render(componentProps, this.__rwcbPublicRef) : Component(componentProps);
        this.__rwcbMount.replaceChildren(renderVNode(vnode));
        this.__rwcbRunEffects(this.__rwcbLayoutEffects);
        queueMicrotask(() => this.__rwcbRunEffects(this.__rwcbEffects));
      } finally {
        __rwcbCurrentInstance = previous;
      }
    }

    __rwcbCreateEventProps() {
      const props = {};
      for (const [propName, definition] of Object.entries(eventOptions)) {
        props[propName] = (...args) => {
          const detail = typeof definition?.detail === "function" ? definition.detail(...args) : args[0];
          this.dispatchEvent(new CustomEvent(definition?.name || toKebab(propName.replace(/^on/, "")), { detail, bubbles: true, composed: true }));
        };
      }
      return props;
    }

    __rwcbCreateSlotProps() {
      const props = {};
      for (const [propName, definition] of Object.entries(slotOptions)) {
        const name = definition === true ? undefined : typeof definition === "string" ? definition : definition?.name;
        props[propName] = h("slot", name ? { name } : {});
      }
      return props;
    }

    useState(initialValue) {
      const index = this.__rwcbHookIndex++;
      if (!(index in this.__rwcbHooks)) {
        this.__rwcbHooks[index] = typeof initialValue === "function" ? initialValue() : initialValue;
      }
      const setValue = (nextValue) => {
        const currentValue = this.__rwcbHooks[index];
        this.__rwcbHooks[index] = typeof nextValue === "function" ? nextValue(currentValue) : nextValue;
        this.__rwcbScheduleRender();
      };
      return [this.__rwcbHooks[index], setValue];
    }

    useMemo(factory, deps) {
      const index = this.__rwcbHookIndex++;
      const record = this.__rwcbHooks[index];
      if (!record || !depsEqual(record.deps, deps)) {
        this.__rwcbHooks[index] = { deps, value: factory() };
      }
      return this.__rwcbHooks[index].value;
    }

    useRef(initialValue) {
      const index = this.__rwcbHookIndex++;
      if (!(index in this.__rwcbHooks)) this.__rwcbHooks[index] = { current: initialValue };
      return this.__rwcbHooks[index];
    }

    useEffect(effect, deps, layout) {
      const index = this.__rwcbHookIndex++;
      const record = this.__rwcbHooks[index];
      if (record && depsEqual(record.deps, deps)) return;
      if (record && typeof record.cleanup === "function") record.cleanup();
      this.__rwcbHooks[index] = { deps, cleanup: undefined };
      const queue = layout ? this.__rwcbLayoutEffects : this.__rwcbEffects;
      queue.push(() => {
        const cleanup = effect();
        this.__rwcbHooks[index].cleanup = typeof cleanup === "function" ? cleanup : undefined;
      });
    }

    useId() {
      const index = this.__rwcbHookIndex++;
      if (!(index in this.__rwcbHooks)) this.__rwcbHooks[index] = this.__rwcbIdPrefix + "-" + index;
      return this.__rwcbHooks[index];
    }

    __rwcbReadContext(context) {
      return this.__rwcbContextValues.has(context) ? this.__rwcbContextValues.get(context) : context.defaultValue;
    }

    __rwcbPushContext(context, value) {
      const previous = this.__rwcbContextValues.has(context)
        ? { exists: true, value: this.__rwcbContextValues.get(context) }
        : { exists: false, value: undefined };
      this.__rwcbContextValues.set(context, value);
      return () => {
        if (previous.exists) this.__rwcbContextValues.set(context, previous.value);
        else this.__rwcbContextValues.delete(context);
      };
    }

    __rwcbTrackPortal(container) {
      this.__rwcbPortalContainers.push(container);
    }

    __rwcbCleanupPortals() {
      for (const container of this.__rwcbPortalContainers) container.remove();
      this.__rwcbPortalContainers = [];
    }

    __rwcbRunEffects(effects) {
      for (const effect of effects) effect();
    }
  }

  for (const name of Object.keys(propOptions)) {
    Object.defineProperty(CompiledReactElement.prototype, name, {
      get() { return this.__rwcbProps[name]; },
      set(value) {
        this.__rwcbProps[name] = value;
        this.__rwcbScheduleRender();
      }
    });
  }

  for (const [name, definition] of Object.entries(options.methods || {})) {
    Object.defineProperty(CompiledReactElement.prototype, name, {
      value(...args) {
        if (typeof definition?.call === "function") {
          if (definition.call.length <= 1) return definition.call(this.__rwcbPublicHandle || this);
          return definition.call(this.__rwcbPublicHandle || this, this, ...args);
        }
      }
    });
  }

  if (!customElements.get(tagName)) customElements.define(tagName, CompiledReactElement);
  return CompiledReactElement;
}

function renderVNode(vnode) {
  if (vnode == null || vnode === false || vnode === true) return document.createTextNode("");
  if (Array.isArray(vnode)) {
    const fragment = document.createDocumentFragment();
    for (const child of vnode) fragment.append(renderVNode(child));
    return fragment;
  }
  if (typeof vnode === "string" || typeof vnode === "number") return document.createTextNode(String(vnode));
  if (vnode.type === ContextProvider) {
    const restore = __rwcbCurrentInstance.__rwcbPushContext(vnode.props.context, vnode.props.value);
    try {
      return renderVNode(vnode.children);
    } finally {
      restore();
    }
  }
  if (vnode.type === SuspenseBoundary) {
    const previous = __rwcbCurrentSuspenseFallback;
    __rwcbCurrentSuspenseFallback = vnode.props.fallback;
    try {
      return renderVNode(vnode.children);
    } finally {
      __rwcbCurrentSuspenseFallback = previous;
    }
  }
  if (vnode.type === Portal) {
    const target = typeof vnode.props.target === "function" ? vnode.props.target() : vnode.props.target;
    if (!target) return document.createTextNode("");
    const container = document.createElement("span");
    container.setAttribute("data-rwcb-portal", "");
    target.append(container);
    __rwcbCurrentInstance?.__rwcbTrackPortal(container);
    container.replaceChildren(renderVNode(vnode.children));
    return document.createTextNode("");
  }
  if (typeof vnode.type === "function") return renderVNode(vnode.type({ ...vnode.props, children: vnode.children }));
  if (vnode.type?.__rwcbForwardRef) return renderVNode(vnode.type.render({ ...vnode.props, children: vnode.children }, createRef()));
  if (vnode.type === Fragment) return renderVNode(vnode.children);
  const element = document.createElement(vnode.type);
  applyProps(element, vnode.props);
  for (const child of vnode.children || []) element.append(renderVNode(child));
  return element;
}

function applyProps(element, props) {
  for (const [name, value] of Object.entries(props || {})) {
    if (name === "children" || name === "key" || value == null || value === false) continue;
    if (name === "className") {
      element.setAttribute("class", value);
    } else if (name === "htmlFor") {
      element.setAttribute("for", value);
    } else if (name === "ref" && typeof value === "object") {
      value.current = element;
    } else if (name === "style" && typeof value === "object") {
      Object.assign(element.style, value);
    } else if (/^on[A-Z]/.test(name) && typeof value === "function") {
      element.addEventListener(name.slice(2).toLowerCase(), value);
    } else if (name in element && typeof value !== "object") {
      element[name] = value;
    } else if (value === true) {
      element.setAttribute(name, "");
    } else {
      element.setAttribute(name, String(value));
    }
  }
}

function normalizeChildren(children) {
  if (children == null || children === false || children === true) return [];
  return Array.isArray(children) ? children.flat(Infinity) : [children];
}

function parseAttribute(value, definition = {}) {
  if (definition.type === "boolean") return value !== null;
  if (value === null) return undefined;
  if (definition.type === "number") return Number(value);
  if (definition.type === "json") {
    try { return JSON.parse(value); } catch { return definition.default; }
  }
  return value;
}

function applyStyles(root, styles) {
  if (!styles) return;
  const style = document.createElement("style");
  style.textContent = Array.isArray(styles) ? styles.join("\n") : String(styles);
  root.prepend(style);
}

function depsEqual(previous, next) {
  return Array.isArray(previous) && Array.isArray(next) && previous.length === next.length && previous.every((value, index) => Object.is(value, next[index]));
}

function toKebab(value) {
  return value.replace(/[A-Z]/g, (match) => "-" + match.toLowerCase()).replace(/^-/, "");
}

function MetricCard({ label = "Revenue", value = 128, delta = 12, onInspect }) {
    const tone = useMemo(() => (delta >= 0 ? "positive" : "negative"), [delta]);
    return (h("article", { className: `metric-card metric-card--${tone}` },
        h("span", { className: "metric-card__label" }, label),
        h("strong", { className: "metric-card__value" }, value),
        h("small", { className: "metric-card__delta" },
            delta >= 0 ? "+" : "",
            delta,
            "%"),
        h("button", { onClick: () => onInspect?.({ label, value }) }, "Inspect")));
}


defineComponentTag("demo-metric-card", MetricCard, {"shadow":{"mode":"open"},"props":{"label":{"type":"string","reflect":true},"value":{"type":"number","reflect":true},"delta":{"type":"number","reflect":true}},"events":{"onInspect":{"name":"inspect"}},"styles":":host{display:block}.metric-card{border:1px solid #d9e2ec;padding:1rem;border-radius:.5rem}.metric-card--positive{border-color:#10b981}.metric-card--negative{border-color:#ef4444}"});