import type { ReactElementMetadata } from "@fahimc/react-web-component-bridge";

export type GeneratorOutput = {
  customElementsJson: string;
  declarations: string;
  markdown: string;
};

export function generateArtifacts(metadata: readonly ReactElementMetadata[]): GeneratorOutput {
  return {
    customElementsJson: JSON.stringify(
      {
        schemaVersion: "2.1.0",
        readme: "",
        modules: metadata.map((item) => ({
          kind: "javascript-module",
          path: item.tagName,
          declarations: [
            {
              kind: "class",
              name: `${pascal(item.tagName)}Element`,
              tagName: item.tagName,
              customElement: true,
              attributes: item.attributes,
              events: item.events,
              slots: item.slots,
              members: item.properties.map((property) => ({
                kind: "field",
                name: property.name,
                type: { text: property.type ?? "unknown" },
                required: property.required
              }))
            }
          ]
        }))
      },
      null,
      2
    ),
    declarations: createDeclarations(metadata),
    markdown: createMarkdown(metadata)
  };
}

function createDeclarations(metadata: readonly ReactElementMetadata[]): string {
  const eventTypes = metadata
    .flatMap((item) =>
      item.events.map(
        (event) =>
          `export type ${pascal(item.tagName)}${pascal(event.name)}Event = CustomEvent<unknown>;`
      )
    )
    .join("\n");
  const tagMap = metadata.map((item) => `    "${item.tagName}": HTMLElement;`).join("\n");
  return [
    "/* Generated by react-web-component-bridge generate. */",
    eventTypes,
    "declare global {",
    "  interface HTMLElementTagNameMap {",
    tagMap,
    "  }",
    "}",
    "export {};"
  ].join("\n");
}

function createMarkdown(metadata: readonly ReactElementMetadata[]): string {
  return metadata
    .map((item) =>
      [
        `## ${item.tagName}`,
        "",
        "| Kind | Name | Detail |",
        "| --- | --- | --- |",
        ...item.properties.map(
          (property) => `| property | ${property.name} | ${property.type ?? ""} |`
        ),
        ...item.attributes.map(
          (attribute) => `| attribute | ${attribute.name} | ${attribute.property} |`
        ),
        ...item.events.map((event) => `| event | ${event.name} | ${event.prop} |`),
        ...item.slots.map((slot) => `| slot | ${slot.name ?? "default"} | ${slot.prop} |`),
        ...item.methods.map((method) => `| method | ${method.name} | public method |`)
      ].join("\n")
    )
    .join("\n\n");
}

function pascal(value: string): string {
  return value
    .split(/[-_\s]/)
    .filter(Boolean)
    .map((part) => part[0]?.toUpperCase() + part.slice(1))
    .join("");
}
